[package]
name = "sql-generustor"
version = "0.1.3"
edition = "2024"
authors = ["Harupi <hvrupi@proton.me>"]
license = "MIT"
description = "A tool to generate SQL insertion commands"
readme = "README.md"
homepage = "https://github.com/Hvrnbi/sql-generustor"
repository = "https://github.com/Hvrnbi/sql-generustor"
keywords = ["cli", "sql", "generation", "insert", "insertion"]
categories = ["command-line-utilities"]

[package.metadata.bundle]
identifier = "me.harupi.sql-generustor"
copyright = "MIT License - 2026 Harupi"
category = "public.app-category.developer-tools"
linux_use_terminal = true

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
fastrand = "2.4.1"
random_word = { version = "0.5.2", features = ["fr"] }
unaccent = "0.1.1"
